/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeTravelRouteImport } from './routes/time-travel'
import { Route as SideQuestsRouteImport } from './routes/side-quests'
import { Route as ChessRouteImport } from './routes/chess'
import { Route as IndexRouteImport } from './routes/index'

const TimeTravelRoute = TimeTravelRouteImport.update({
  id: '/time-travel',
  path: '/time-travel',
  getParentRoute: () => rootRouteImport,
} as any)
const SideQuestsRoute = SideQuestsRouteImport.update({
  id: '/side-quests',
  path: '/side-quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessRoute = ChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chess': typeof ChessRoute
  '/side-quests': typeof SideQuestsRoute
  '/time-travel': typeof TimeTravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chess': typeof ChessRoute
  '/side-quests': typeof SideQuestsRoute
  '/time-travel': typeof TimeTravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chess': typeof ChessRoute
  '/side-quests': typeof SideQuestsRoute
  '/time-travel': typeof TimeTravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chess' | '/side-quests' | '/time-travel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chess' | '/side-quests' | '/time-travel'
  id: '__root__' | '/' | '/chess' | '/side-quests' | '/time-travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChessRoute: typeof ChessRoute
  SideQuestsRoute: typeof SideQuestsRoute
  TimeTravelRoute: typeof TimeTravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-travel': {
      id: '/time-travel'
      path: '/time-travel'
      fullPath: '/time-travel'
      preLoaderRoute: typeof TimeTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-quests': {
      id: '/side-quests'
      path: '/side-quests'
      fullPath: '/side-quests'
      preLoaderRoute: typeof SideQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess': {
      id: '/chess'
      path: '/chess'
      fullPath: '/chess'
      preLoaderRoute: typeof ChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChessRoute: ChessRoute,
  SideQuestsRoute: SideQuestsRoute,
  TimeTravelRoute: TimeTravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
